/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"


/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_UART0_Init();
	SC_TWI0_Init();
	SC_TIM2_Init();
	SC_PWM0_Init();
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(16000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC32F10xSx_NIO_Init();
	OPTION_LVRConfig(OPTION_LVR_4_3V);
	/*Init Struct*/OPTION_JTAGCmd(DISABLE);
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_IFB,DISABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PC04 Struct*/GPIO_InitTypeDef GPIOInit_PC04_Struct;
	GPIOInit_PC04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PC04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC04_Struct);/*PC.04端口初始化*/
	/*GPIOInit_PC05 Struct*/GPIO_InitTypeDef GPIOInit_PC05_Struct;
	GPIOInit_PC05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PC05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC05_Struct);/*PC.05端口初始化*/
	/*GPIOInit_PC10 Struct*/GPIO_InitTypeDef GPIOInit_PC10_Struct;
	GPIOInit_PC10_Struct.GPIO_Pin = GPIO_Pin_10;
	GPIOInit_PC10_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC10_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC10_Struct);/*PC.10端口初始化*/
	/*GPIOInit_PC11 Struct*/GPIO_InitTypeDef GPIOInit_PC11_Struct;
	GPIOInit_PC11_Struct.GPIO_Pin = GPIO_Pin_11;
	GPIOInit_PC11_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC11_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC11_Struct);/*PC.11端口初始化*/
	/*GPIOInit_PA07 Struct*/GPIO_InitTypeDef GPIOInit_PA07_Struct;
	GPIOInit_PA07_Struct.GPIO_Pin = GPIO_Pin_7;
	GPIOInit_PA07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA07_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA07_Struct);/*PA.07端口初始化*/
	/*GPIOInit_PA08 Struct*/GPIO_InitTypeDef GPIOInit_PA08_Struct;
	GPIOInit_PA08_Struct.GPIO_Pin = GPIO_Pin_8;
	GPIOInit_PA08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA08_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA08_Struct);/*PA.08端口初始化*/
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PC02 Struct*/GPIO_InitTypeDef GPIOInit_PC02_Struct;
	GPIOInit_PC02_Struct.GPIO_Pin = GPIO_Pin_2;
	GPIOInit_PC02_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC02_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC02_Struct);/*RX0端口初始化*/
	/*GPIOInit_PC03 Struct*/GPIO_InitTypeDef GPIOInit_PC03_Struct;
	GPIOInit_PC03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PC03_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC03_Struct);/*TX0端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_UART0, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode = UART_Mode_10B;
	UART_Init(UART0, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART0,UART_IT_EN,DISABLE);
	/*INT_TX*/UART_ITConfig(UART0,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART0,UART_IT_RX,DISABLE);
	/*DMA_TX*/UART_DMACmd(UART0,UART_DMAReq_TX,DISABLE);
	/*DMA_RX*/UART_DMACmd(UART0,UART_DMAReq_RX,DISABLE);
	/*Init Struct*/UART_PinRemapConfig(UART0,UART_PinRemap_Default);
	UART_TXCmd(UART0,ENABLE);
	UART_RXCmd(UART0,ENABLE);
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#if defined (SC32f12xx)

/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#endif

/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM2,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_2;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 12768;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM2, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM2, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM2, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_PWMA;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM2, &TIM_PWM_InitStruct);
	TIM_PinRemapConfig(TIM2, TIM_PinRemap_Default);
	TIM_PWMSetDuty(TIM2, TIM_PWMChannel_PWMA,80);
	/*INTEN*/TIM_ITConfig(TIM2,TIM_IT_INTEN, ENABLE);
	/*EXR*/TIM_ITConfig(TIM2,TIM_IT_EXR,DISABLE);
	/*EXF*/TIM_ITConfig(TIM2,TIM_IT_EXF,DISABLE);
	/*TI*/TIM_ITConfig(TIM2,TIM_IT_TI,ENABLE);
	/*CAPR*/TIM_DMACmd(TIM2,TIM_DMAReq_CAPR,DISABLE);
	/*CAPF*/TIM_DMACmd(TIM2,TIM_DMAReq_CAPF,DISABLE);
	/*TI*/TIM_DMACmd(TIM2,TIM_DMAReq_TI,DISABLE);
	TIM_Cmd(TIM2,DISABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_PWM0,ENABLE);
	/*PWM00*/PWM_SetDuty(PWM0,PWM_Channel_0,0);
	/*PWM01*/PWM_SetDuty(PWM0,PWM_Channel_1,800);
	/*PWM02*/PWM_SetDuty(PWM0,PWM_Channel_2,600);
	/*PWM03*/PWM_SetDuty(PWM0,PWM_Channel_3,100);
	/*PWM04*/PWM_SetDuty(PWM0,PWM_Channel_4,0);
	/*PWM05*/PWM_SetDuty(PWM0,PWM_Channel_5,0);
	/*PWM06*/PWM_SetDuty(PWM0,PWM_Channel_6,0);
	/*PWM07*/PWM_SetDuty(PWM0,PWM_Channel_7,0);
	/*Init Struct*/PWM_InitTypeDef PWM_InitStruct;
	PWM_InitStruct.PWM_WorkMode = PWM_WorkMode_Independent;
	PWM_InitStruct.PWM_Prescaler = PWM_PRESCALER_DIV1;
	PWM_InitStruct.PWM_Cycle = 1000;
	PWM_InitStruct.PWM_OutputChannel = PWMChannel_Less|PWM_Channel_1|PWM_Channel_2|PWM_Channel_3;
	PWM_InitStruct.PWM_LowPolarityChannl = PWMChannel_Less;
	PWM_InitStruct.PWM_AlignedMode = PWM_AlignmentMode_Edge;
	PWM_Init(PWM0,&PWM_InitStruct);
	/*Init Struct*/PWM_FDInitTypeDef PWM_FDInitStruct;
	PWM_FDInitStruct.PWM_FDMode = PWM_FDMode_Immediate;
	PWM_FDInitStruct.PWM_FDVoltage = PWM_FDVoltage_Low;
	PWM_FDInitStruct.PWM_FDFilteringTime = PWM_FilteringTime_0us;
	PWM_FDInit(PWM0, &PWM_FDInitStruct);
	PWM_FDCmd(PWM0,DISABLE);
	/*INTEN*/PWM_ITConfig(PWM0,PWM_IT_INTEN,DISABLE);
	PWM_Cmd(PWM0,ENABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#if defined (SC32f12xx)

/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

#endif

/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PA05 Struct*/GPIO_InitTypeDef GPIOInit_PA05_Struct;
	GPIOInit_PA05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PA05_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA05_Struct);/*SDA0B端口初始化*/
	/*GPIOInit_PA06 Struct*/GPIO_InitTypeDef GPIOInit_PA06_Struct;
	GPIOInit_PA06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PA06_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA06_Struct);/*SCL0B端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TWI0, ENABLE);
	/*Init Struct*/TWI_InitTypeDef TWI_InitStruct;
	TWI_InitStruct.TWI_Ack = TWI_Ack_Enable;
	TWI_InitStruct.TWI_Prescaler = TWI_PRESCALER_2048;
	TWI_InitStruct.TWI_Stretch = TWI_Stretch_Disable;
	TWI_InitStruct.TWI_SlaveAdress = 0x01;
	TWI_InitStruct.TWI_GeneralCall = TWI_GeneralCall_Disable;
	TWI_Init(TWI0, &TWI_InitStruct);
	TWI_PinRemapConfig(TWI0,TWI_PinRemap_B);
	/*INT*/TWI_ITConfig(TWI0,TWI_IT_INT,ENABLE);
	/*DMA_TX*/TWI_DMACmd(TWI0,TWI_DMAReq_TX,DISABLE);
	/*DMA_RX*/TWI_DMACmd(TWI0,TWI_DMAReq_RX,DISABLE);
	/*Init Struct*/NVIC_SetPriority(TWI0_IRQn,3);/*TWI0*/
	NVIC_EnableIRQ(TWI0_IRQn);
	TWI_Cmd(TWI0,ENABLE);
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}


/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}
#if defined (SC32f10xx)

/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}
#endif

/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief LCD init
  * @note 
  * @param
  */
void SC_LCD_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief SC_LED_Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ACMP init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}
#if defined (SC32f12xx)

/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

#endif





























